sidekiq_scheduler:
  check_date_job:
    cron: "* * * * *"
    class: "CheckDateJob"
    queue: "default"
    description: "Check date every hour"

  update_post_status_job:
    cron: "0 * * * *"
    class: "UpdatePostStatusJob"
  #bundle exec sidekiq -r ./config/environment.rb
