sidekiq_scheduler:
  check_date_job:
    cron: "* * * * *"
    class: "CheckDateJob"
    queue: "default"
    description: "Check date every hour"

  update_post_status_job:
    cron: "0 * * * *"
    class: "UpdatePostStatusJob"
    queue: "default"
    description: "Check time every minute"

  check_time_job:
    cron: "0 * * * *"
    class: "CheckTimeJob"
    queue: "default"
    description: "Check time every minute"
<<<<<<< HEAD

  every_tf_job:
    cron: "0 0 * * *"
    class: "EveryTfJob"
    queue: "default"
    description: "Check something every hour"
=======
>>>>>>> ee172af7 (Modified the aims in the README)
#bundle exec sidekiq -r ./config/environment.rb
