sidekiq_scheduler:
  check_date_job:
    cron: "* * * * *"
    class: "CheckDateJob"
    queue: "default"
    description: "Check date every hour"

  update_post_status_job:
    cron: "0 * * * *"
    class: "UpdatePostStatusJob"
    queue: "default"
    description: "Check time every minute"

  check_time_job:
    cron: "0 * * * *"
    class: "CheckTimeJob"
    queue: "default"
    description: "Check time every minute"

  every_tf_job:
    cron: "0 0 * * *"
    class: "EveryTfJob"
    queue: "default"
    description: "Check something every hour"

  clean_notification_job:
    cron: "0 * * * *"
    class: "CleanNotificationJob"
    queue: "default"
    description: "Insert a description GAB"
#bundle exec sidekiq -r ./config/environment.rb
