sidekiq_scheduler:
  check_date_job:
    cron: "0 9/1 * * *"
    class: "CheckDateJob"
    queue: "default"
    description: "Check date every six hours"

  update_post_status_job:
    cron: "0 * * * *"
    class: "UpdatePostStatusJob"
  #bundle exec sidekiq -r ./config/environment.rb
