sidekiq_scheduler:
  check_date_job:
    cron: "* * * * *"
    class: "CheckDateJob"
    queue: "default"
    description: "Check date every hour"

  update_post_status_job:
    cron: "0 * * * *"
    class: "UpdatePostStatusJob"

  check_time_job:
    cron: "0 * * * *"
    class: "CheckTimeJob"
    queue: "default"
    description: "Check time every minute"
#bundle exec sidekiq -r ./config/environment.rb
